/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CredentialIssuer

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param atContext 
 * @param id 
 * @param type 
 * @param issuer 
 * @param issuanceDate 
 * @param expirationDate 
 * @param credentialSubject 
 */


data class CredentialIssuanceRequestCredential (

    @Json(name = "@context")
    val atContext: kotlin.collections.List<kotlin.String>,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "type")
    val type: kotlin.collections.List<kotlin.String>,

    @Json(name = "issuer")
    val issuer: CredentialIssuer,

    @Json(name = "issuanceDate")
    val issuanceDate: kotlin.String,

    @Json(name = "expirationDate")
    val expirationDate: kotlin.String,

    @Json(name = "credentialSubject")
    val credentialSubject: kotlin.collections.Map<kotlin.String, kotlin.Any>

)

