/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param created 
 * @param challenge 
 * @param domain 
 * @param nonce 
 * @param verificationMethod 
 * @param proofPurpose 
 * @param jws 
 * @param proofValue 
 */


data class CredentialProof (

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "created")
    val created: kotlin.String,

    @Json(name = "challenge")
    val challenge: kotlin.String,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "nonce")
    val nonce: kotlin.String,

    @Json(name = "verificationMethod")
    val verificationMethod: kotlin.String,

    @Json(name = "proofPurpose")
    val proofPurpose: kotlin.String,

    @Json(name = "jws")
    val jws: kotlin.String,

    @Json(name = "proofValue")
    val proofValue: kotlin.String

)

