/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CredentialIssuanceRequestCredential
import org.openapitools.client.models.CredentialIssuanceRequestOptions

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param credential 
 * @param options 
 */


data class CredentialIssuanceRequest (

    @Json(name = "credential")
    val credential: CredentialIssuanceRequestCredential,

    @Json(name = "options")
    val options: CredentialIssuanceRequestOptions

)

