/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CredentialStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param created 
 * @param challenge 
 * @param domain 
 * @param credentialStatus 
 */


data class CredentialIssuanceRequestOptions (

    @Json(name = "created")
    val created: kotlin.String,

    @Json(name = "challenge")
    val challenge: kotlin.String,

    @Json(name = "domain")
    val domain: kotlin.String,

    @Json(name = "credentialStatus")
    val credentialStatus: CredentialStatus

)

